### ISSUE TITLE
A new type of visitor

### ISSUE THREAD

**Issue by plotn** [eb4j/dsl4j#65]
Hi!
It is me again. Analyzing lingvo dsl card format there is:

[labels](http://lingvo.helpmax.net/en/troubleshooting/glossary/#mark) (optional)
[translations zone](http://lingvo.helpmax.net/en/troubleshooting/dsl-compiler/marking-of-zones-for-full-text-search/#translate)
[comments zone](http://lingvo.helpmax.net/en/troubleshooting/dsl-compiler/marking-of-zones-for-full-text-search/#comment) (optional)
[examples zone](http://lingvo.helpmax.net/en/troubleshooting/dsl-compiler/marking-of-zones-for-full-text-search/#example) (optional)
[pictures or sound](http://lingvo.helpmax.net/en/troubleshooting/dsl-compiler/inserting-pictures-and-sounds/) (optional)
[links to Web pages](http://lingvo.helpmax.net/en/troubleshooting/dsl-compiler/inserting-internet-links/) (optional)

For me it would be suitable to split these zones to separate objects within DslEntry, e.g.:
DslEntry.translations (arraylist)
DslEntry.examples (arraylist)
etc...

And ability to convert these parts to text/html separately.

Reason - my reading app displays these parts separately.

**Comment by miurahr** [comment]
you can copy HtmlDslVisitor to your project and modify it to fit to your requirements.

Hint HtmlDslVisitor is defined to returning String
so it is defined
```java
public class HtmlDslVisitor extends DslVisitor<String> {
```

If you defines your data class such as
```java
public PlotnData {
   List<String> translations;
   List<String> examples;
}
```
and define visitor to be return your data object.
```
public class PlotnVisitor extends DslVisitor<PlotnData> {
}
```

```java
    @Override
    public void start() {
        plotnData = new PlotnData();
    }

    @Override
    public void finish() {
    }
```

And define getObject() class

```java
public PlotnData getObject() {
}
```

**Comment by miurahr** [comment]
Answered.
